## Min-Max Scaling and Standardization:

In [1]:
import numpy as np

# Sample data
data = np.array([[10, 20], [15, 25], [30, 35]])

print("Original Data:\n", data)

Original Data:
 [[10 20]
 [15 25]
 [30 35]]


from sklearn.preprocessing import MinMaxScaler

# Min-Max Scaling
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

print("Min-Max Scaled Data:\n", scaled_data)

In [2]:
from sklearn.preprocessing import StandardScaler

# Standardization
standardizer = StandardScaler()
standardized_data = standardizer.fit_transform(data)

In [3]:
print("Standardized Data:\n", standardized_data)

Standardized Data:
 [[-0.98058068 -1.06904497]
 [-0.39223227 -0.26726124]
 [ 1.37281295  1.33630621]]


In [26]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Sample categorical data
categories = np.array([['Alice'], ['Bob'], ['Alice'], ['David'],['Eve']])
df = pd.DataFrame(categories)

print('Original Data:\n', df.to_string(header=False, index=False))




Original Data:
 Alice
  Bob
Alice
David
  Eve


In [24]:
from sklearn.preprocessing import OneHotEncoder

# One-Hot Encoding
encoder = OneHotEncoder(sparse=False)
encoded_data = encoder.fit_transform(df)

C:\Users\VioletaAtanasova\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [25]:

print("One-Hot Encoded Data:\n", encoded_data)

One-Hot Encoded Data:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
