## Arrays

In [2]:
import numpy as np

# Creating a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Displaying the array
array


array([1, 2, 3, 4, 5])

## Multi-dimensional Arrays

In [5]:
# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Displaying the matrix
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Mathematical Operations

In [6]:
# Element-wise operations
array = np.array([1, 2, 3, 4])
array_squared = array ** 2

# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)

# Displaying the results
print("Squared array:", array_squared)
print("Matrix multiplication result:\n", result)


Squared array: [ 1  4  9 16]
Matrix multiplication result:
 [[19 22]
 [43 50]]
